apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: monolith-checkpoint-pvc
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: standard-rwo
  resources:
    requests:
      storage: 10Gi